#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hastane")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_Bolum(Tbl_Bolum instance);
    partial void UpdateTbl_Bolum(Tbl_Bolum instance);
    partial void DeleteTbl_Bolum(Tbl_Bolum instance);
    partial void InsertTbl_Doktor(Tbl_Doktor instance);
    partial void UpdateTbl_Doktor(Tbl_Doktor instance);
    partial void DeleteTbl_Doktor(Tbl_Doktor instance);
    partial void InsertTbl_Eczaci(Tbl_Eczaci instance);
    partial void UpdateTbl_Eczaci(Tbl_Eczaci instance);
    partial void DeleteTbl_Eczaci(Tbl_Eczaci instance);
    partial void InsertTbl_Hasta(Tbl_Hasta instance);
    partial void UpdateTbl_Hasta(Tbl_Hasta instance);
    partial void DeleteTbl_Hasta(Tbl_Hasta instance);
    partial void InsertTbl_ilac(Tbl_ilac instance);
    partial void UpdateTbl_ilac(Tbl_ilac instance);
    partial void DeleteTbl_ilac(Tbl_ilac instance);
    partial void InsertTbl_Sekreter(Tbl_Sekreter instance);
    partial void UpdateTbl_Sekreter(Tbl_Sekreter instance);
    partial void DeleteTbl_Sekreter(Tbl_Sekreter instance);
    partial void InsertTbl_Unvan(Tbl_Unvan instance);
    partial void UpdateTbl_Unvan(Tbl_Unvan instance);
    partial void DeleteTbl_Unvan(Tbl_Unvan instance);
    partial void InsertTbl_User(Tbl_User instance);
    partial void UpdateTbl_User(Tbl_User instance);
    partial void DeleteTbl_User(Tbl_User instance);
    #endregion
		
		public dbDataContext() : 
				base(global::WindowsFormsApp3.Properties.Settings.Default.hastaneConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Bolum> Tbl_Bolums
		{
			get
			{
				return this.GetTable<Tbl_Bolum>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Doktor> Tbl_Doktors
		{
			get
			{
				return this.GetTable<Tbl_Doktor>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Eczaci> Tbl_Eczacis
		{
			get
			{
				return this.GetTable<Tbl_Eczaci>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Hasta> Tbl_Hastas
		{
			get
			{
				return this.GetTable<Tbl_Hasta>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_ilac> Tbl_ilacs
		{
			get
			{
				return this.GetTable<Tbl_ilac>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sekreter> Tbl_Sekreters
		{
			get
			{
				return this.GetTable<Tbl_Sekreter>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Unvan> Tbl_Unvans
		{
			get
			{
				return this.GetTable<Tbl_Unvan>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_User> Tbl_Users
		{
			get
			{
				return this.GetTable<Tbl_User>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Recete> Tbl_Recetes
		{
			get
			{
				return this.GetTable<Tbl_Recete>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Bolum")]
	public partial class Tbl_Bolum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _bolumAdi;
		
		private string _bolumKisaltma;
		
		private EntitySet<Tbl_Sekreter> _Tbl_Sekreters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbolumAdiChanging(string value);
    partial void OnbolumAdiChanged();
    partial void OnbolumKisaltmaChanging(string value);
    partial void OnbolumKisaltmaChanged();
    #endregion
		
		public Tbl_Bolum()
		{
			this._Tbl_Sekreters = new EntitySet<Tbl_Sekreter>(new Action<Tbl_Sekreter>(this.attach_Tbl_Sekreters), new Action<Tbl_Sekreter>(this.detach_Tbl_Sekreters));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolumAdi", DbType="NVarChar(50)")]
		public string bolumAdi
		{
			get
			{
				return this._bolumAdi;
			}
			set
			{
				if ((this._bolumAdi != value))
				{
					this.OnbolumAdiChanging(value);
					this.SendPropertyChanging();
					this._bolumAdi = value;
					this.SendPropertyChanged("bolumAdi");
					this.OnbolumAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolumKisaltma", DbType="NVarChar(50)")]
		public string bolumKisaltma
		{
			get
			{
				return this._bolumKisaltma;
			}
			set
			{
				if ((this._bolumKisaltma != value))
				{
					this.OnbolumKisaltmaChanging(value);
					this.SendPropertyChanging();
					this._bolumKisaltma = value;
					this.SendPropertyChanged("bolumKisaltma");
					this.OnbolumKisaltmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Bolum_Tbl_Sekreter", Storage="_Tbl_Sekreters", ThisKey="id", OtherKey="sekreterBolumid")]
		public EntitySet<Tbl_Sekreter> Tbl_Sekreters
		{
			get
			{
				return this._Tbl_Sekreters;
			}
			set
			{
				this._Tbl_Sekreters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Sekreters(Tbl_Sekreter entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Bolum = this;
		}
		
		private void detach_Tbl_Sekreters(Tbl_Sekreter entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Bolum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Doktor")]
	public partial class Tbl_Doktor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _doktorAdi;
		
		private string _doktorSoyadi;
		
		private string _doktorTel;
		
		private System.Nullable<int> _doktorBolumid;
		
		private System.Nullable<int> _doktorUnvanid;
		
		private System.Nullable<int> _doktorSekreterid;
		
		private System.Nullable<int> _doktorUserid;
		
		private EntityRef<Tbl_Sekreter> _Tbl_Sekreter;
		
		private EntityRef<Tbl_Unvan> _Tbl_Unvan;
		
		private EntityRef<Tbl_User> _Tbl_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndoktorAdiChanging(string value);
    partial void OndoktorAdiChanged();
    partial void OndoktorSoyadiChanging(string value);
    partial void OndoktorSoyadiChanged();
    partial void OndoktorTelChanging(string value);
    partial void OndoktorTelChanged();
    partial void OndoktorBolumidChanging(System.Nullable<int> value);
    partial void OndoktorBolumidChanged();
    partial void OndoktorUnvanidChanging(System.Nullable<int> value);
    partial void OndoktorUnvanidChanged();
    partial void OndoktorSekreteridChanging(System.Nullable<int> value);
    partial void OndoktorSekreteridChanged();
    partial void OndoktorUseridChanging(System.Nullable<int> value);
    partial void OndoktorUseridChanged();
    #endregion
		
		public Tbl_Doktor()
		{
			this._Tbl_Sekreter = default(EntityRef<Tbl_Sekreter>);
			this._Tbl_Unvan = default(EntityRef<Tbl_Unvan>);
			this._Tbl_User = default(EntityRef<Tbl_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doktorAdi", DbType="NVarChar(50)")]
		public string doktorAdi
		{
			get
			{
				return this._doktorAdi;
			}
			set
			{
				if ((this._doktorAdi != value))
				{
					this.OndoktorAdiChanging(value);
					this.SendPropertyChanging();
					this._doktorAdi = value;
					this.SendPropertyChanged("doktorAdi");
					this.OndoktorAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doktorSoyadi", DbType="NVarChar(50)")]
		public string doktorSoyadi
		{
			get
			{
				return this._doktorSoyadi;
			}
			set
			{
				if ((this._doktorSoyadi != value))
				{
					this.OndoktorSoyadiChanging(value);
					this.SendPropertyChanging();
					this._doktorSoyadi = value;
					this.SendPropertyChanged("doktorSoyadi");
					this.OndoktorSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doktorTel", DbType="NVarChar(15)")]
		public string doktorTel
		{
			get
			{
				return this._doktorTel;
			}
			set
			{
				if ((this._doktorTel != value))
				{
					this.OndoktorTelChanging(value);
					this.SendPropertyChanging();
					this._doktorTel = value;
					this.SendPropertyChanged("doktorTel");
					this.OndoktorTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doktorBolumid", DbType="Int")]
		public System.Nullable<int> doktorBolumid
		{
			get
			{
				return this._doktorBolumid;
			}
			set
			{
				if ((this._doktorBolumid != value))
				{
					this.OndoktorBolumidChanging(value);
					this.SendPropertyChanging();
					this._doktorBolumid = value;
					this.SendPropertyChanged("doktorBolumid");
					this.OndoktorBolumidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doktorUnvanid", DbType="Int")]
		public System.Nullable<int> doktorUnvanid
		{
			get
			{
				return this._doktorUnvanid;
			}
			set
			{
				if ((this._doktorUnvanid != value))
				{
					if (this._Tbl_Unvan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndoktorUnvanidChanging(value);
					this.SendPropertyChanging();
					this._doktorUnvanid = value;
					this.SendPropertyChanged("doktorUnvanid");
					this.OndoktorUnvanidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doktorSekreterid", DbType="Int")]
		public System.Nullable<int> doktorSekreterid
		{
			get
			{
				return this._doktorSekreterid;
			}
			set
			{
				if ((this._doktorSekreterid != value))
				{
					if (this._Tbl_Sekreter.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndoktorSekreteridChanging(value);
					this.SendPropertyChanging();
					this._doktorSekreterid = value;
					this.SendPropertyChanged("doktorSekreterid");
					this.OndoktorSekreteridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doktorUserid", DbType="Int")]
		public System.Nullable<int> doktorUserid
		{
			get
			{
				return this._doktorUserid;
			}
			set
			{
				if ((this._doktorUserid != value))
				{
					if (this._Tbl_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndoktorUseridChanging(value);
					this.SendPropertyChanging();
					this._doktorUserid = value;
					this.SendPropertyChanged("doktorUserid");
					this.OndoktorUseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sekreter_Tbl_Doktor", Storage="_Tbl_Sekreter", ThisKey="doktorSekreterid", OtherKey="id", IsForeignKey=true)]
		public Tbl_Sekreter Tbl_Sekreter
		{
			get
			{
				return this._Tbl_Sekreter.Entity;
			}
			set
			{
				Tbl_Sekreter previousValue = this._Tbl_Sekreter.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sekreter.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sekreter.Entity = null;
						previousValue.Tbl_Doktors.Remove(this);
					}
					this._Tbl_Sekreter.Entity = value;
					if ((value != null))
					{
						value.Tbl_Doktors.Add(this);
						this._doktorSekreterid = value.id;
					}
					else
					{
						this._doktorSekreterid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Sekreter");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Unvan_Tbl_Doktor", Storage="_Tbl_Unvan", ThisKey="doktorUnvanid", OtherKey="id", IsForeignKey=true)]
		public Tbl_Unvan Tbl_Unvan
		{
			get
			{
				return this._Tbl_Unvan.Entity;
			}
			set
			{
				Tbl_Unvan previousValue = this._Tbl_Unvan.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Unvan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Unvan.Entity = null;
						previousValue.Tbl_Doktors.Remove(this);
					}
					this._Tbl_Unvan.Entity = value;
					if ((value != null))
					{
						value.Tbl_Doktors.Add(this);
						this._doktorUnvanid = value.id;
					}
					else
					{
						this._doktorUnvanid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Unvan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_Doktor", Storage="_Tbl_User", ThisKey="doktorUserid", OtherKey="id", IsForeignKey=true)]
		public Tbl_User Tbl_User
		{
			get
			{
				return this._Tbl_User.Entity;
			}
			set
			{
				Tbl_User previousValue = this._Tbl_User.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_User.Entity = null;
						previousValue.Tbl_Doktors.Remove(this);
					}
					this._Tbl_User.Entity = value;
					if ((value != null))
					{
						value.Tbl_Doktors.Add(this);
						this._doktorUserid = value.id;
					}
					else
					{
						this._doktorUserid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Eczaci")]
	public partial class Tbl_Eczaci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _eczaciAdi;
		
		private string _eczaciSoyadi;
		
		private string _eczaciTel;
		
		private string _eczaciAdresi;
		
		private System.Nullable<int> _eczaciUserid;
		
		private EntityRef<Tbl_User> _Tbl_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OneczaciAdiChanging(string value);
    partial void OneczaciAdiChanged();
    partial void OneczaciSoyadiChanging(string value);
    partial void OneczaciSoyadiChanged();
    partial void OneczaciTelChanging(string value);
    partial void OneczaciTelChanged();
    partial void OneczaciAdresiChanging(string value);
    partial void OneczaciAdresiChanged();
    partial void OneczaciUseridChanging(System.Nullable<int> value);
    partial void OneczaciUseridChanged();
    #endregion
		
		public Tbl_Eczaci()
		{
			this._Tbl_User = default(EntityRef<Tbl_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eczaciAdi", DbType="NVarChar(50)")]
		public string eczaciAdi
		{
			get
			{
				return this._eczaciAdi;
			}
			set
			{
				if ((this._eczaciAdi != value))
				{
					this.OneczaciAdiChanging(value);
					this.SendPropertyChanging();
					this._eczaciAdi = value;
					this.SendPropertyChanged("eczaciAdi");
					this.OneczaciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eczaciSoyadi", DbType="NVarChar(50)")]
		public string eczaciSoyadi
		{
			get
			{
				return this._eczaciSoyadi;
			}
			set
			{
				if ((this._eczaciSoyadi != value))
				{
					this.OneczaciSoyadiChanging(value);
					this.SendPropertyChanging();
					this._eczaciSoyadi = value;
					this.SendPropertyChanged("eczaciSoyadi");
					this.OneczaciSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eczaciTel", DbType="NVarChar(50)")]
		public string eczaciTel
		{
			get
			{
				return this._eczaciTel;
			}
			set
			{
				if ((this._eczaciTel != value))
				{
					this.OneczaciTelChanging(value);
					this.SendPropertyChanging();
					this._eczaciTel = value;
					this.SendPropertyChanged("eczaciTel");
					this.OneczaciTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eczaciAdresi", DbType="NVarChar(100)")]
		public string eczaciAdresi
		{
			get
			{
				return this._eczaciAdresi;
			}
			set
			{
				if ((this._eczaciAdresi != value))
				{
					this.OneczaciAdresiChanging(value);
					this.SendPropertyChanging();
					this._eczaciAdresi = value;
					this.SendPropertyChanged("eczaciAdresi");
					this.OneczaciAdresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eczaciUserid", DbType="Int")]
		public System.Nullable<int> eczaciUserid
		{
			get
			{
				return this._eczaciUserid;
			}
			set
			{
				if ((this._eczaciUserid != value))
				{
					if (this._Tbl_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OneczaciUseridChanging(value);
					this.SendPropertyChanging();
					this._eczaciUserid = value;
					this.SendPropertyChanged("eczaciUserid");
					this.OneczaciUseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_Eczaci", Storage="_Tbl_User", ThisKey="eczaciUserid", OtherKey="id", IsForeignKey=true)]
		public Tbl_User Tbl_User
		{
			get
			{
				return this._Tbl_User.Entity;
			}
			set
			{
				Tbl_User previousValue = this._Tbl_User.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_User.Entity = null;
						previousValue.Tbl_Eczacis.Remove(this);
					}
					this._Tbl_User.Entity = value;
					if ((value != null))
					{
						value.Tbl_Eczacis.Add(this);
						this._eczaciUserid = value.id;
					}
					else
					{
						this._eczaciUserid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Hasta")]
	public partial class Tbl_Hasta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _hastaAdi;
		
		private string _hastaSoyadi;
		
		private string _hastaTel;
		
		private string _hastaAdres;
		
		private System.Nullable<int> _hastaUserid;
		
		private EntityRef<Tbl_User> _Tbl_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhastaAdiChanging(string value);
    partial void OnhastaAdiChanged();
    partial void OnhastaSoyadiChanging(string value);
    partial void OnhastaSoyadiChanged();
    partial void OnhastaTelChanging(string value);
    partial void OnhastaTelChanged();
    partial void OnhastaAdresChanging(string value);
    partial void OnhastaAdresChanged();
    partial void OnhastaUseridChanging(System.Nullable<int> value);
    partial void OnhastaUseridChanged();
    #endregion
		
		public Tbl_Hasta()
		{
			this._Tbl_User = default(EntityRef<Tbl_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaAdi", DbType="NVarChar(50)")]
		public string hastaAdi
		{
			get
			{
				return this._hastaAdi;
			}
			set
			{
				if ((this._hastaAdi != value))
				{
					this.OnhastaAdiChanging(value);
					this.SendPropertyChanging();
					this._hastaAdi = value;
					this.SendPropertyChanged("hastaAdi");
					this.OnhastaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaSoyadi", DbType="NVarChar(50)")]
		public string hastaSoyadi
		{
			get
			{
				return this._hastaSoyadi;
			}
			set
			{
				if ((this._hastaSoyadi != value))
				{
					this.OnhastaSoyadiChanging(value);
					this.SendPropertyChanging();
					this._hastaSoyadi = value;
					this.SendPropertyChanged("hastaSoyadi");
					this.OnhastaSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaTel", DbType="NVarChar(15)")]
		public string hastaTel
		{
			get
			{
				return this._hastaTel;
			}
			set
			{
				if ((this._hastaTel != value))
				{
					this.OnhastaTelChanging(value);
					this.SendPropertyChanging();
					this._hastaTel = value;
					this.SendPropertyChanged("hastaTel");
					this.OnhastaTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaAdres", DbType="NVarChar(50)")]
		public string hastaAdres
		{
			get
			{
				return this._hastaAdres;
			}
			set
			{
				if ((this._hastaAdres != value))
				{
					this.OnhastaAdresChanging(value);
					this.SendPropertyChanging();
					this._hastaAdres = value;
					this.SendPropertyChanged("hastaAdres");
					this.OnhastaAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaUserid", DbType="Int")]
		public System.Nullable<int> hastaUserid
		{
			get
			{
				return this._hastaUserid;
			}
			set
			{
				if ((this._hastaUserid != value))
				{
					if (this._Tbl_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhastaUseridChanging(value);
					this.SendPropertyChanging();
					this._hastaUserid = value;
					this.SendPropertyChanged("hastaUserid");
					this.OnhastaUseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_Hasta", Storage="_Tbl_User", ThisKey="hastaUserid", OtherKey="id", IsForeignKey=true)]
		public Tbl_User Tbl_User
		{
			get
			{
				return this._Tbl_User.Entity;
			}
			set
			{
				Tbl_User previousValue = this._Tbl_User.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_User.Entity = null;
						previousValue.Tbl_Hastas.Remove(this);
					}
					this._Tbl_User.Entity = value;
					if ((value != null))
					{
						value.Tbl_Hastas.Add(this);
						this._hastaUserid = value.id;
					}
					else
					{
						this._hastaUserid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_ilac")]
	public partial class Tbl_ilac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ilacAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnilacAdiChanging(string value);
    partial void OnilacAdiChanged();
    #endregion
		
		public Tbl_ilac()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilacAdi", DbType="NVarChar(50)")]
		public string ilacAdi
		{
			get
			{
				return this._ilacAdi;
			}
			set
			{
				if ((this._ilacAdi != value))
				{
					this.OnilacAdiChanging(value);
					this.SendPropertyChanging();
					this._ilacAdi = value;
					this.SendPropertyChanged("ilacAdi");
					this.OnilacAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sekreter")]
	public partial class Tbl_Sekreter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sekreterAdi;
		
		private string _sekreterSoyadi;
		
		private System.Nullable<int> _sekreterBolumid;
		
		private System.Nullable<int> _sekreterUserid;
		
		private EntitySet<Tbl_Doktor> _Tbl_Doktors;
		
		private EntityRef<Tbl_Bolum> _Tbl_Bolum;
		
		private EntityRef<Tbl_User> _Tbl_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsekreterAdiChanging(string value);
    partial void OnsekreterAdiChanged();
    partial void OnsekreterSoyadiChanging(string value);
    partial void OnsekreterSoyadiChanged();
    partial void OnsekreterBolumidChanging(System.Nullable<int> value);
    partial void OnsekreterBolumidChanged();
    partial void OnsekreterUseridChanging(System.Nullable<int> value);
    partial void OnsekreterUseridChanged();
    #endregion
		
		public Tbl_Sekreter()
		{
			this._Tbl_Doktors = new EntitySet<Tbl_Doktor>(new Action<Tbl_Doktor>(this.attach_Tbl_Doktors), new Action<Tbl_Doktor>(this.detach_Tbl_Doktors));
			this._Tbl_Bolum = default(EntityRef<Tbl_Bolum>);
			this._Tbl_User = default(EntityRef<Tbl_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sekreterAdi", DbType="NVarChar(50)")]
		public string sekreterAdi
		{
			get
			{
				return this._sekreterAdi;
			}
			set
			{
				if ((this._sekreterAdi != value))
				{
					this.OnsekreterAdiChanging(value);
					this.SendPropertyChanging();
					this._sekreterAdi = value;
					this.SendPropertyChanged("sekreterAdi");
					this.OnsekreterAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sekreterSoyadi", DbType="NVarChar(50)")]
		public string sekreterSoyadi
		{
			get
			{
				return this._sekreterSoyadi;
			}
			set
			{
				if ((this._sekreterSoyadi != value))
				{
					this.OnsekreterSoyadiChanging(value);
					this.SendPropertyChanging();
					this._sekreterSoyadi = value;
					this.SendPropertyChanged("sekreterSoyadi");
					this.OnsekreterSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sekreterBolumid", DbType="Int")]
		public System.Nullable<int> sekreterBolumid
		{
			get
			{
				return this._sekreterBolumid;
			}
			set
			{
				if ((this._sekreterBolumid != value))
				{
					if (this._Tbl_Bolum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsekreterBolumidChanging(value);
					this.SendPropertyChanging();
					this._sekreterBolumid = value;
					this.SendPropertyChanged("sekreterBolumid");
					this.OnsekreterBolumidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sekreterUserid", DbType="Int")]
		public System.Nullable<int> sekreterUserid
		{
			get
			{
				return this._sekreterUserid;
			}
			set
			{
				if ((this._sekreterUserid != value))
				{
					if (this._Tbl_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsekreterUseridChanging(value);
					this.SendPropertyChanging();
					this._sekreterUserid = value;
					this.SendPropertyChanged("sekreterUserid");
					this.OnsekreterUseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sekreter_Tbl_Doktor", Storage="_Tbl_Doktors", ThisKey="id", OtherKey="doktorSekreterid")]
		public EntitySet<Tbl_Doktor> Tbl_Doktors
		{
			get
			{
				return this._Tbl_Doktors;
			}
			set
			{
				this._Tbl_Doktors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Bolum_Tbl_Sekreter", Storage="_Tbl_Bolum", ThisKey="sekreterBolumid", OtherKey="id", IsForeignKey=true)]
		public Tbl_Bolum Tbl_Bolum
		{
			get
			{
				return this._Tbl_Bolum.Entity;
			}
			set
			{
				Tbl_Bolum previousValue = this._Tbl_Bolum.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Bolum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Bolum.Entity = null;
						previousValue.Tbl_Sekreters.Remove(this);
					}
					this._Tbl_Bolum.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sekreters.Add(this);
						this._sekreterBolumid = value.id;
					}
					else
					{
						this._sekreterBolumid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Bolum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_Sekreter", Storage="_Tbl_User", ThisKey="sekreterUserid", OtherKey="id", IsForeignKey=true)]
		public Tbl_User Tbl_User
		{
			get
			{
				return this._Tbl_User.Entity;
			}
			set
			{
				Tbl_User previousValue = this._Tbl_User.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_User.Entity = null;
						previousValue.Tbl_Sekreters.Remove(this);
					}
					this._Tbl_User.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sekreters.Add(this);
						this._sekreterUserid = value.id;
					}
					else
					{
						this._sekreterUserid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Doktors(Tbl_Doktor entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sekreter = this;
		}
		
		private void detach_Tbl_Doktors(Tbl_Doktor entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sekreter = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Unvan")]
	public partial class Tbl_Unvan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _unvanAdi;
		
		private string _unvanKisaltma;
		
		private EntitySet<Tbl_Doktor> _Tbl_Doktors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnunvanAdiChanging(string value);
    partial void OnunvanAdiChanged();
    partial void OnunvanKisaltmaChanging(string value);
    partial void OnunvanKisaltmaChanged();
    #endregion
		
		public Tbl_Unvan()
		{
			this._Tbl_Doktors = new EntitySet<Tbl_Doktor>(new Action<Tbl_Doktor>(this.attach_Tbl_Doktors), new Action<Tbl_Doktor>(this.detach_Tbl_Doktors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unvanAdi", DbType="NVarChar(50)")]
		public string unvanAdi
		{
			get
			{
				return this._unvanAdi;
			}
			set
			{
				if ((this._unvanAdi != value))
				{
					this.OnunvanAdiChanging(value);
					this.SendPropertyChanging();
					this._unvanAdi = value;
					this.SendPropertyChanged("unvanAdi");
					this.OnunvanAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unvanKisaltma", DbType="NVarChar(50)")]
		public string unvanKisaltma
		{
			get
			{
				return this._unvanKisaltma;
			}
			set
			{
				if ((this._unvanKisaltma != value))
				{
					this.OnunvanKisaltmaChanging(value);
					this.SendPropertyChanging();
					this._unvanKisaltma = value;
					this.SendPropertyChanged("unvanKisaltma");
					this.OnunvanKisaltmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Unvan_Tbl_Doktor", Storage="_Tbl_Doktors", ThisKey="id", OtherKey="doktorUnvanid")]
		public EntitySet<Tbl_Doktor> Tbl_Doktors
		{
			get
			{
				return this._Tbl_Doktors;
			}
			set
			{
				this._Tbl_Doktors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Doktors(Tbl_Doktor entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Unvan = this;
		}
		
		private void detach_Tbl_Doktors(Tbl_Doktor entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Unvan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_User")]
	public partial class Tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<short> _userType;
		
		private EntitySet<Tbl_Doktor> _Tbl_Doktors;
		
		private EntitySet<Tbl_Eczaci> _Tbl_Eczacis;
		
		private EntitySet<Tbl_Hasta> _Tbl_Hastas;
		
		private EntitySet<Tbl_Sekreter> _Tbl_Sekreters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnuserTypeChanging(System.Nullable<short> value);
    partial void OnuserTypeChanged();
    #endregion
		
		public Tbl_User()
		{
			this._Tbl_Doktors = new EntitySet<Tbl_Doktor>(new Action<Tbl_Doktor>(this.attach_Tbl_Doktors), new Action<Tbl_Doktor>(this.detach_Tbl_Doktors));
			this._Tbl_Eczacis = new EntitySet<Tbl_Eczaci>(new Action<Tbl_Eczaci>(this.attach_Tbl_Eczacis), new Action<Tbl_Eczaci>(this.detach_Tbl_Eczacis));
			this._Tbl_Hastas = new EntitySet<Tbl_Hasta>(new Action<Tbl_Hasta>(this.attach_Tbl_Hastas), new Action<Tbl_Hasta>(this.detach_Tbl_Hastas));
			this._Tbl_Sekreters = new EntitySet<Tbl_Sekreter>(new Action<Tbl_Sekreter>(this.attach_Tbl_Sekreters), new Action<Tbl_Sekreter>(this.detach_Tbl_Sekreters));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userType", DbType="SmallInt")]
		public System.Nullable<short> userType
		{
			get
			{
				return this._userType;
			}
			set
			{
				if ((this._userType != value))
				{
					this.OnuserTypeChanging(value);
					this.SendPropertyChanging();
					this._userType = value;
					this.SendPropertyChanged("userType");
					this.OnuserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_Doktor", Storage="_Tbl_Doktors", ThisKey="id", OtherKey="doktorUserid")]
		public EntitySet<Tbl_Doktor> Tbl_Doktors
		{
			get
			{
				return this._Tbl_Doktors;
			}
			set
			{
				this._Tbl_Doktors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_Eczaci", Storage="_Tbl_Eczacis", ThisKey="id", OtherKey="eczaciUserid")]
		public EntitySet<Tbl_Eczaci> Tbl_Eczacis
		{
			get
			{
				return this._Tbl_Eczacis;
			}
			set
			{
				this._Tbl_Eczacis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_Hasta", Storage="_Tbl_Hastas", ThisKey="id", OtherKey="hastaUserid")]
		public EntitySet<Tbl_Hasta> Tbl_Hastas
		{
			get
			{
				return this._Tbl_Hastas;
			}
			set
			{
				this._Tbl_Hastas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_Sekreter", Storage="_Tbl_Sekreters", ThisKey="id", OtherKey="sekreterUserid")]
		public EntitySet<Tbl_Sekreter> Tbl_Sekreters
		{
			get
			{
				return this._Tbl_Sekreters;
			}
			set
			{
				this._Tbl_Sekreters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Doktors(Tbl_Doktor entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = this;
		}
		
		private void detach_Tbl_Doktors(Tbl_Doktor entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = null;
		}
		
		private void attach_Tbl_Eczacis(Tbl_Eczaci entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = this;
		}
		
		private void detach_Tbl_Eczacis(Tbl_Eczaci entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = null;
		}
		
		private void attach_Tbl_Hastas(Tbl_Hasta entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = this;
		}
		
		private void detach_Tbl_Hastas(Tbl_Hasta entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = null;
		}
		
		private void attach_Tbl_Sekreters(Tbl_Sekreter entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = this;
		}
		
		private void detach_Tbl_Sekreters(Tbl_Sekreter entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Recete")]
	public partial class Tbl_Recete
	{
		
		private int _id;
		
		private System.Nullable<int> _hastaid;
		
		private System.Nullable<int> _doktorid;
		
		private System.Nullable<int> _sekreterid;
		
		private System.Nullable<int> _ilacid;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		public Tbl_Recete()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaid", DbType="Int")]
		public System.Nullable<int> hastaid
		{
			get
			{
				return this._hastaid;
			}
			set
			{
				if ((this._hastaid != value))
				{
					this._hastaid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doktorid", DbType="Int")]
		public System.Nullable<int> doktorid
		{
			get
			{
				return this._doktorid;
			}
			set
			{
				if ((this._doktorid != value))
				{
					this._doktorid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sekreterid", DbType="Int")]
		public System.Nullable<int> sekreterid
		{
			get
			{
				return this._sekreterid;
			}
			set
			{
				if ((this._sekreterid != value))
				{
					this._sekreterid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilacid", DbType="Int")]
		public System.Nullable<int> ilacid
		{
			get
			{
				return this._ilacid;
			}
			set
			{
				if ((this._ilacid != value))
				{
					this._ilacid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this._Tarih = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
